2018-04-21 00:52:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://target.com> (referer: None)
Traceback (most recent call last):
  File "/home/cs5331/.local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/cs5331/.local/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 30, in process_spider_output
    for x in result:
  File "/home/cs5331/.local/lib/python2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/cs5331/.local/lib/python2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/cs5331/.local/lib/python2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/cs5331/.local/lib/python2.7/site-packages/scrapy/spiders/crawl.py", line 82, in _parse_response
    for request_or_item in self._requests_to_follow(response):
  File "/home/cs5331/.local/lib/python2.7/site-packages/scrapy/spiders/crawl.py", line 60, in _requests_to_follow
    for n, rule in enumerate(self._rules):
AttributeError: 'benchmarkSpider' object has no attribute '_rules'
